version: '3.4'

services:
  sqlserver:
    build:
      context: .
      dockerfile: SqlServer_DockerFile
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SenhaForte12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P SenhaForte12345 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ThomasGregDB;User Id=sa;Password=SenhaForte12345;
    networks:
          - app-network

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge